name: Criterion.rs Example
on:
  push:
    branches:
      - master

permissions:
  contents: write
  deployments: write

jobs:
  benchmark:
    name: Run Criterion.rs benchmark example
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: rustup toolchain update nightly && rustup default nightly
      - name: Run benchmark
        run: cargo bench -- --output-format bencher | tee output.txt

      - name: Store benchmark result
        uses: benchmark-action/github-action-benchmark@v1.14.0
        with:
          name: Rust Benchmark
          tool: "cargo"
          output-file-path: output.txt
          github-token: ${{ secrets.BENCHMARK_TOKEN }}
          auto-push: false
          gh-repository: "https://github.com/IWANABETHATGUY/stats"

          # Show alert with commit comment on detecting possible performance regression
          fail-on-alert: false

      # - name: Push benchmark result
      #   run: git push 'https://IWANABETHATGUY:${{ secrets.GITHUB_TOKEN }}@github.com/IWANABETHATGUY/benchmark-gh-action-rs.git' gh-pages:gh-pages

# name: rust benchmark
# # on: [pull_request]
# on:
#   issue_comment:
#     types:
#       - created

# jobs:
#   benchmark:
#     name: Run Rust benchmark example
#     runs-on: ubuntu-latest
#     # if: ${{ github.event.comment.body == 'comment'}}
#     if: github.event.issue.pull_request && contains(github.event.comment.body, '!bench')
#     steps:
#       - uses: actions/checkout@v2
#       - run: rustup toolchain update nightly && rustup default nightly
#       - name: Run benchmark
#         run: cargo +nightly bench | tee output.txt
#       - name: Store benchmark result
#         uses: rhysd/github-action-benchmark@v1
#         with:
#           name: Rust Benchmark
#           tool: 'cargo'
#           output-file-path: output.txt
#           # Use personal access token instead of GITHUB_TOKEN due to https://github.community/t5/GitHub-Actions/Github-action-not-triggering-gh-pages-upon-push/td-p/26869/highlight/false
#           github-token: ${{ secrets.BENCHMARK_TOKEN }}
#           auto-push: true
#           # Show alert with commit comment on detecting possible performance regression
#           alert-threshold: '5%'
#           comment-on-alert: true
#           fail-on-alert: true
#           alert-comment-cc-users: '@IWANABETHATGUY'
